#!/bin/csh -f
# $Id: smk_mkdir,v 1.5 2011/04/22 14:34:29 bbaek Exp $

   ### Set umask to be group writable, world read and execute
   umask 2

   ### Make input and output director(ies) #######
   if ( -e $SMKDAT ) then
  #shc if( ! -e $INVDIR/area ) mkdir -p $INVDIR/area
  #shc if( ! -e $INVDIR/nonroad ) mkdir -p $INVDIR/nonroad
  #shc if( ! -e $INVDIR/biog ) mkdir -p $INVDIR/biog
  #shc if( ! -e $INVDIR/point ) mkdir -p $INVDIR/point
  #shc if( ! -e $INVDIR/mobile ) mkdir -p $INVDIR/mobile
  #shc if( ! -e $INVDIR/other ) mkdir -p $INVDIR/other
       if( ! -e $GE_DAT ) mkdir -p $GE_DAT
       if( ! -e $INVOPD ) mkdir -p $INVOPD
 #shc  if( ! -e $A_OUT )  mkdir -p $A_OUT
 #shc  if( ! -e $B_OUT )  mkdir -p $B_OUT
 #shc  if( ! -e $M_OUT )  mkdir -p $M_OUT
 #shc  if( ! -e $P_OUT )  mkdir -p $P_OUT
       if( ! -e $SCENARIO ) mkdir -p $SCENARIO
       if( ! -e $STATIC ) mkdir -p $STATIC
       if( ! -e $OUTPUT ) mkdir -p $OUTPUT
       if( ! -e $SMK_TMPDIR ) mkdir -p $SMK_TMPDIR  
       if( ! -e $LOGS   ) mkdir -p $LOGS  
       if( ! -e $BASDIR ) mkdir -p $BASDIR
       if( ! -e $REPSCEN ) mkdir -p $REPSCEN
       if( ! -e $REPSTAT ) mkdir -p $REPSTAT
       if( ! -e $REPSTAT ) mkdir -p $REPSTAT
       if (! -e $OUTPUT/$MBASE/static ) mkdir -p  $OUTPUT/$MBASE/static
 #shc  if( ! -e $REPORTS/$ASCEN/scenario ) mkdir -p $REPORTS/$ASCEN/scenario
 #shc  if( ! -e $REPORTS/$ASCEN/static )  mkdir -p $REPORTS/$ASCEN/static
 #shc  if( ! -e $REPORTS/$BSCEN/scenario ) mkdir -p $REPORTS/$BSCEN/scenario
 #shc  if( ! -e $REPORTS/$MSCEN/scenario ) mkdir -p $REPORTS/$MSCEN/scenario
 #shc  if( ! -e $REPORTS/$MSCEN/static )  mkdir -p $REPORTS/$MSCEN/static
 #shc  if( ! -e $REPORTS/$PSCEN/scenario ) mkdir -p $REPORTS/$PSCEN/scenario
 #shc  if( ! -e $REPORTS/$PSCEN/static )  mkdir -p $REPORTS/$PSCEN/static
   else
       echo "ERROR: The SMOKE data directory does not exist!"
       echo "       Please check to make sure that the following"
       echo "       path is valid:"
       echo "       $SMKDAT"
       exit( 1 )
   endif


   cd $ASSIGNS
